# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 413a319a9c0b264c98285dcbe17dfe43b9914abe2ab70669ad9d1beee64c145809a779584127c29affb1de51a90f6eb9d767eddca882f9565ff47c6416d9a267

test:
  secret_key_base: 63281c1c53438c3a2755ef87539d64be1b6b1c113174d2c8dd36277e4964490a6afddffab9aff211ac1cd9b77c67f42faef2a8e2ec7b8723f614a9494b1517fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
